### ISSUE TITLE
Test connection succeeds, but opening database throw connection error

### ISSUE THREAD

**Issue by jlenon7** [HongJinFeng/RedisManager#10]
I'm trying to connect to a redis database, everything goes well when testing the connection

![Captura de Tela 2021-12-19 às 12 50 08](https://user-images.githubusercontent.com/52840235/146681495-10e3384b-15be-41ed-b5ca-b654ebcb1e49.png)

But when I try to connect, I get this error in the IDE. I'm using DataGrip.

![Captura de Tela 2021-12-19 às 12 53 21](https://user-images.githubusercontent.com/52840235/146681527-49ef4fbf-c68b-40a6-998a-456cffb59adc.png)

**Comment by HongJinFeng** [comment]
Hi. What is your version.

**Comment by HongJinFeng** [comment]
> 

Hi. What is your plugin version? Try to delete username. And connect again.

**Comment by jlenon7** [comment]
Hi, thank you so much for the reply @HongJinFeng 😊

My version is 1.3.8, I think it's the latest. Deleting the username and trying to connect again doesn't work. Every time I try to change the username, it always stays "redis".

I saw this issue here: https://github.com/redis/node-redis/issues/1591#issuecomment-812672883

I change the username to "default", but whenever I press OK to save the changes in the connection, the username goes back to just "redis". I get the same problem when deleting the username completely.

See: 
https://drive.google.com/file/d/17bXJwtNfEGg-JvkAONFhogjVqeQVExiT/view?usp=sharing

**Comment by HongJinFeng** [comment]
Hi, thanks for your video, it help me a lot. I fixed the edit username issue, please update to version 1.3.9 and try again. Besides, try set username default or delete username or change redis server to no auth and connect again.

**Comment by jlenon7** [comment]
Fixed in version 1.3.9! Thank you so much @HongJinFeng, good work! 😊
