### ISSUE TITLE
The scroll does not work in the Redis Manager

### ISSUE THREAD

**Issue by an2riy** [HongJinFeng/RedisManager#11]
The scroll does not work in the Redis Manager.
It is always located at the TOP when the mouse wheel is used to scroll.

**Environment:**
PhpStorm 2021.3
Build #PS-213.5744.279, built on December 2, 2021
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-43-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2944M
Cores: 12
Registry:
    debugger.watches.in.variables=false
    editor.caret.width=1
    run.processes.with.pty=TRUE
    ide.experimental.ui.toolwindow.stripes=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.1)
    pronskiy.elephpant (0.1.1)
    org.elasticsearch4idea (1.7.1-2021.2)
    name.kropp.intellij.makefile (213.5744.224)
    ir.msdehghan.plugins.ansible (0.92)
    io.github.az1a.reminder (0.3)
    indent-rainbow.indent-rainbow (1.7.0)
    com.ultrahob.zerolength.plugin (0.95)
    com.intellij.ideolog (203.0.27.0)
    com.intellij.properties (213.5744.121)
    com.mallowigi (53.0.0)
    com.hjf.redis.manager.redis-manager (1.3.9)
    com.alayouni.ansiHighlight (1.2.4)
    String Manipulation (8.23.203.000.0)
    zielu.gittoolbox (212.8.4)
    mobi.hsz.idea.gitignore (4.3.0)
    de.espend.idea.php.annotation (8.0.0)
    com.kalessil.phpStorm.phpInspectionsUltimate-mp (2021.5)
    fr.adrienbrault.idea.symfony2plugin (0.23.213)
    com.magento.idea.magento2plugin (4.2.1)
    lv.midiana.misc.phpstorm-plugins.deep-keys (2021.07.18.002)
    izhangzhihao.rainbow.brackets (6.21)
    com.chrisrm.idea.MaterialThemeUI (6.12.2)
    org.jetbrains.plugins.node-remote-interpreter (213.5744.122)
    ru.adelf.idea.dotenv (2021.3.0.213)

Current Desktop: ubuntu:GNOME

![image](https://user-images.githubusercontent.com/8819844/147648240-8b97eb6c-63dd-474c-b12e-199a29fa78c5.png)

**Comment by HongJinFeng** [comment]
> The scroll does not work in the Redis Manager. It is always located at the TOP when the mouse wheel is used to scroll.
> 
> **Environment:** PhpStorm 2021.3 Build #PS-213.5744.279, built on December 2, 2021 Runtime version: 11.0.13+7-b1751.19 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Linux 5.11.0-43-generic GC: G1 Young Generation, G1 Old Generation Memory: 2944M Cores: 12 Registry: debugger.watches.in.variables=false editor.caret.width=1 run.processes.with.pty=TRUE ide.experimental.ui.toolwindow.stripes=true ide.balloon.shadow.size=0
> 
> Non-Bundled Plugins: ski.chrzanow.foldableprojectview (1.1.1) pronskiy.elephpant (0.1.1) org.elasticsearch4idea (1.7.1-2021.2) name.kropp.intellij.makefile (213.5744.224) ir.msdehghan.plugins.ansible (0.92) io.github.az1a.reminder (0.3) indent-rainbow.indent-rainbow (1.7.0) com.ultrahob.zerolength.plugin (0.95) com.intellij.ideolog (203.0.27.0) com.intellij.properties (213.5744.121) com.mallowigi (53.0.0) com.hjf.redis.manager.redis-manager (1.3.9) com.alayouni.ansiHighlight (1.2.4) String Manipulation (8.23.203.000.0) zielu.gittoolbox (212.8.4) mobi.hsz.idea.gitignore (4.3.0) de.espend.idea.php.annotation (8.0.0) com.kalessil.phpStorm.phpInspectionsUltimate-mp (2021.5) fr.adrienbrault.idea.symfony2plugin (0.23.213) com.magento.idea.magento2plugin (4.2.1) lv.midiana.misc.phpstorm-plugins.deep-keys (2021.07.18.002) izhangzhihao.rainbow.brackets (6.21) com.chrisrm.idea.MaterialThemeUI (6.12.2) org.jetbrains.plugins.node-remote-interpreter (213.5744.122) ru.adelf.idea.dotenv (2021.3.0.213)
> 
> Current Desktop: ubuntu:GNOME
> 
> ![image](https://user-images.githubusercontent.com/8819844/147648240-8b97eb6c-63dd-474c-b12e-199a29fa78c5.png)

Please accept apologies for the inconvenience this has caused! I am working on a fix, so it should be addressed as soon as possible. Thanks for your support!

**Comment by an2riy** [comment]
Thanks

**Comment by hwooo** [comment]
I have same issue.

**Comment by HongJinFeng** [comment]
> Thanks
@an2riy 
Hi. I fixed this issue on version 1.4.0. Please update plugin to the newest version. Thanks for your report. Besides, can you please revoke the three-star review? It means a lot to plugin developer. And here is a 20% OFF coupon code(9BLVL-FSH4Y-26G4D-3H4BR-73ETS) for you if you want to subscribe next time. Anyway, Feel free to talk if you has any other problem or suggestion.

**Comment by HongJinFeng** [comment]
> Hi. I fixed this issue on version 1.4.0. Please update plugin to the newest version. Thanks for your report.
@hwooo 
Hi. I fixed this issue on version 1.4.0. Please update plugin to the newest version. Thanks for your report.

**Comment by HongJinFeng** [comment]
> I have same issue.
@hwooo 
Hi. I fixed this issue on version 1.4.0. Please update plugin to the newest version. Thanks for your report.

**Comment by an2riy** [comment]
Confirm.
Thanks for the so quick fix.

**Comment by HongJinFeng** [comment]
> Confirm. Thanks for the so quick fix.

Thanks! Can you please revoke the three-star review(https://plugins.jetbrains.com/plugin/15722-redis-manager/reviews)? It means a lot to plugin developer.
![image](https://user-images.githubusercontent.com/33616750/147917339-28fa6aed-37ba-4173-8c12-51a6dfa72857.png)

**Comment by an2riy** [comment]
Done
