### ISSUE TITLE
Add json view support

### ISSUE THREAD

**Issue by aboutZZ** [HongJinFeng/RedisManager#13]
The value json text is shown as plain text which is unsightly,  any plan of supporting json view?

**Comment by HongJinFeng** [comment]
Thanks for your suggestion. Json view will come next week! @aboutZZ

**Comment by aboutZZ** [comment]
Any updates？

**Comment by HongJinFeng** [comment]
@aboutZZ Hi, please update to version 1.4.1, json view is supported now.
![image](https://user-images.githubusercontent.com/33616750/174443114-17225a0b-9145-4ac3-88f1-fd75fbc79522.png)
