### ISSUE TITLE
来了来了，ssh还是有问题

### ISSUE THREAD

**Issue by YAGAMIL** [HongJinFeng/RedisManager#2]
那个auth是什么意思，用password的时候，还能输入username，切换到privateKey，username就没有了，然后ssh和password使用标签页拆分，我是在ssh这边连的redis，还是ssh这边输入redis的端口，测试链接是测试ssh的链接还是redis的连接
![image](https://user-images.githubusercontent.com/16757285/111720945-e21f2d80-8899-11eb-9b4f-da8f412c1ec5.png)，反正最后试了一下连不上去
![image](https://user-images.githubusercontent.com/16757285/111721489-f0217e00-889a-11eb-8a46-595791906e7c.png)

**Comment by HongJinFeng** [comment]
您好：
&nbsp; &nbsp; &nbsp; &nbsp; Password标签，是直接连接到redis服务器，通过redis的ip和端口连接。
&nbsp; &nbsp; &nbsp; &nbsp; SSH标签，通过ssh登陆跳板机服务器，有两种鉴权模式，一种是通过ssh生成的密钥登陆（ids_pub文件），一种是通过用户名及密码登陆，这里的username和password值的是你服务器39.101.197.184:22的登陆用户名和密码，auth是连接redis的密码，如果没有设置可以不填，这里的如果切换到private_key模式，则不再使用username和password鉴权。测试连接会同时测试ssh连接和redis连接，如果两者其一失败，则测试连接失败。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HongJinFeng/RedisManager"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 上午10:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[HongJinFeng/RedisManager] 来了来了，ssh还是有问题 (#2)





 
那个auth是什么意思，用password的时候，还能输入username，切换到privateKey，username就没有了，然后ssh和password使用标签页拆分，我是在ssh这边连的redis，还是ssh这边输入redis的端口，测试链接是测试ssh的链接还是redis的连接
 ，反正最后试了一下连不上去

**Comment by HongJinFeng** [comment]
@YAGAMIL 
您好：
Password标签，是直接连接到redis服务器，通过redis的ip和端口连接。

SSH标签，通过ssh登陆跳板机服务器，有两种鉴权模式，一种是通过ssh生成的密钥登陆（ids_pub文件），一种是通过用户名及密码登陆，这里的username和password值的是你服务器39.101.197.184:22的登陆用户名和密码，auth是连接redis的密码(非服务器密码，非服务器用户名)，如果没有设置可以不填，这里如果切换到private_key模式，则不再使用username和password鉴权，而是使用密钥文件已经passphrase进行鉴权，passphrase如果没有设置可以不填，测试连接会同时测试ssh连接和redis连接，如果两者其一失败，则测试连接失败。

**Comment by YAGAMIL** [comment]
> @YAGAMIL
> 您好：
> Password标签，是直接连接到redis服务器，通过redis的ip和端口连接。
> 
> SSH标签，通过ssh登陆跳板机服务器，有两种鉴权模式，一种是通过ssh生成的密钥登陆（ids_pub文件），一种是通过用户名及密码登陆，这里的username和password值的是你服务器39.101.197.184:22的登陆用户名和密码，auth是连接redis的密码(非服务器密码，非服务器用户名)，如果没有设置可以不填，这里如果切换到private_key模式，则不再使用username和password鉴权，而是使用密钥文件已经passphrase进行鉴权，passphrase如果没有设置可以不填，测试连接会同时测试ssh连接和redis连接，如果两者其一失败，则测试连接失败。

不呀，即使是通过privatekey登录，也是需要username的老哥

**Comment by HongJinFeng** [comment]
> > @YAGAMIL
> > 您好：
> > Password标签，是直接连接到redis服务器，通过redis的ip和端口连接。
> > SSH标签，通过ssh登陆跳板机服务器，有两种鉴权模式，一种是通过ssh生成的密钥登陆（ids_pub文件），一种是通过用户名及密码登陆，这里的username和password值的是你服务器39.101.197.184:22的登陆用户名和密码，auth是连接redis的密码(非服务器密码，非服务器用户名)，如果没有设置可以不填，这里如果切换到private_key模式，则不再使用username和password鉴权，而是使用密钥文件已经passphrase进行鉴权，passphrase如果没有设置可以不填，测试连接会同时测试ssh连接和redis连接，如果两者其一失败，则测试连接失败。
> 
> 不呀，即使是通过privatekey登录，也是需要username的老哥

你好，请升级到1.2.0版本，已修复该问题。

**Comment by HongJinFeng** [comment]
升级到1.2.0版本，已修复该问题。

**Comment by YAGAMIL** [comment]
> 升级到1.2.0版本，已修复该问题。

不行啊，ssh还是连不上

**Comment by HongJinFeng** [comment]
@YAGAMIL 请问是输入用户名还是连不上吗？看上面的截图，这个private key格式好像不太对。
