### ISSUE TITLE
console中文显示是乱码

### ISSUE THREAD

**Issue by puremdq** [HongJinFeng/RedisManager#3]

**Comment by HongJinFeng** [comment]
1.请问您的操作系统是什么（Windows，Mac OS）
2.请问您的ide是什么，是idea吗。若是，请问您在idea中的字符编码设置是什么（File-&gt;Settings-&gt;Editor-&gt;File Encodings查看）
3.可以尝试设置ide的字符编码为utf-8，如果还是不行，麻烦把第1，2个问题发一下。

**Comment by HongJinFeng** [comment]
> _No description provided._

1.请问您的操作系统是什么（Windows，Mac OS）
2.请问您的ide是什么，是idea吗。若是，请问您在idea中的字符编码设置是什么（File-&gt;Settings-&gt;Editor-&gt;File Encodings查看）
3.可以尝试设置ide的字符编码为utf-8，如果还是不行，麻烦把第1，2个问题发一下。

**Comment by puremdq** [comment]
1.Windows  2.File->Settings->Editor->File Encodings  都设置的utf-8

**Comment by puremdq** [comment]
![image](https://user-images.githubusercontent.com/17739933/112129172-19773c80-8c02-11eb-8305-7a29d1a64ddc.png)

**Comment by HongJinFeng** [comment]
你好，可以截图看一下console的乱码吗？是输入中文就马上变为乱码吗？

**Comment by HongJinFeng** [comment]
@puremdq

**Comment by HongJinFeng** [comment]
你好，可以截图看一下console的乱码吗？是输入中文就马上变为乱码吗？

@puremdq

**Comment by puremdq** [comment]
![image](https://user-images.githubusercontent.com/17739933/112283662-57886500-8cc3-11eb-9379-37af92fd8eea.png)

**Comment by HongJinFeng** [comment]
@puremdq 你好，可以升级到1.2.2版本，已对控制台输出文本进行强制设置了字符编码。可能您的操作系统字符编码是gbk导致的。
