### ISSUE TITLE
为什么无法激活

### ISSUE THREAD

**Issue by teaoea** [HongJinFeng/RedisManager#4]
已经购买redis插件，goland上面可以激活，为什么clion、idea、datagrip上面不能激活，错误There are no valid licenses associated with the account，why？？？？？

**Comment by HongJinFeng** [comment]
> 已经购买redis插件，goland上面可以激活，为什么clion、idea、datagrip上面不能激活，错误There are no valid licenses associated with the account，why？？？？？

您好，请问问题解决了吗？请在idea中的Help-->Register注册激活。 @teaoea

**Comment by HongJinFeng** [comment]
> > 已经购买redis插件，goland上面可以激活，为什么clion、idea、datagrip上面不能激活，错误There are no valid licenses associated with the account，why？？？？？
> 
> 您好，请问问题解决了吗？请在idea中的Help-->Register注册激活。

![image](https://user-images.githubusercontent.com/33616750/117261984-5d0cc980-ae83-11eb-895e-0c3bec678178.png)

**Comment by teaoea** [comment]
下错插件了，有个图标一样的插件，迷惑性太大了😂😂😂

**Comment by teaoea** [comment]
插件安装错了，有个图标一样的插件，迷惑性太大了

**Comment by HongJinFeng** [comment]
> 下错插件了，有个图标一样的插件，迷惑性太大了😂😂😂
> […](#)
> 在 2021年5月6日，15:51，HongJinFeng ***@***.***> 写道： ﻿ 已经购买redis插件，goland上面可以激活，为什么clion、idea、datagrip上面不能激活，错误There are no valid licenses associated with the account，why？？？？？ 您好，请问问题解决了吗？请在idea中的Help-->Register注册激活。 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

好滴，感谢支持。
