### ISSUE TITLE
建议搜索的使用可以使用通配符进行搜索

### ISSUE THREAD

**Issue by YvanBaker** [HongJinFeng/RedisManager#9]
建议在搜索的使用可以使用统配符进行搜索，这样可以更快的搜索到想要的

**Comment by HongJinFeng** [comment]
您好，搜索框之所以用精确匹配，是因为模糊匹配底层用的是redis的scan命令，可能会引起服务阻塞，因此没有使用模糊匹配，如果需要模糊搜索，可以在console命令行里面使用scan命令模糊搜索。

感谢您的支持！！！

**Comment by YvanBaker** [comment]
好的，感谢回复

**Comment by HongJinFeng** [comment]
您好，搜索框支持模糊搜索上线，请更新到最新版本（1.3.3）即可。
